front/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

frontend/frontend/apps/draws/urls.py
from django.urls import path

from . import views
app_name = 'draws'
urlpatterns = [
    # path('draw/', views.draw, name = 'draw'),
    path('', views.index, name='index'),
    path('<int:draw_id>', views.detail, name='detail'),


]

frontend/frontend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('draws/', include('draws.urls')),
    path('',include('draws.urls'))
]

frontend/frontend/apps/draws/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Draw(models.Model):
    block_number = models.IntegerField(blank=True, null=True)
    hash = models.TextField(blank=True, null=True)
    winner_number = models.TextField(blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    members_number = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'draw'


class DrawBets(models.Model):
    user_id = models.IntegerField(blank=True, null=True)
    draw = models.ForeignKey(Draw, on_delete=models.CASCADE)
    number = models.IntegerField(blank=True, null=True)
    btc_address = models.TextField(blank=True, null=True)
    pay = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'draw_bets'


class Lang(models.Model):
    ru = models.TextField(blank=True, null=True)
    en = models.TextField(blank=True, null=True)
    es = models.TextField(blank=True, null=True)
    cn = models.TextField(blank=True, null=True)
    de = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'lang'


class Numbers(models.Model):
    block_number = models.IntegerField(blank=True, null=True)
    hash = models.TextField(blank=True, null=True)
    numbers_block = models.TextField(blank=True, null=True)
    last_number = models.IntegerField(blank=True, null=True)
    five_of_thirty_six = models.IntegerField(blank=True, null=True)
    six_of_forty_five = models.IntegerField(blank=True, null=True)
    timestamp = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'numbers'
        verbose_name = 'Номер'
        verbose_name_plural = 'Номера'


    def __str__(self):
        return self.hash


class Users(models.Model):
    user_id = models.IntegerField(blank=True, null=True)
    first_name = models.TextField(blank=True, null=True)
    user_name = models.TextField(blank=True, null=True)
    language_code = models.TextField(blank=True, null=True)
    language_bot = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    count_visits = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'users'

frontend/frontend/apps/draws/views.py
from django.http import Http404, HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render
from .models import Draw, DrawBets
#

# def draw(request):
#     last_draws = Draw.objects.order_by('block_number')[:15]
#     return render(request, 'draws/list.html', {'last_draws' : last_draws})

def index(request):
    # last_draws = DrawBets.objects.select_related('Draw', 'DrawBets')
    Total = Draw.objects.filter().count()
    if Total > 10:
        last_draws = Draw.objects.order_by('id')[Total-25:Total]
    else:
        last_draws = Draw.objects.order_by('id')[0:10]
    # last_draws = Draw.objects.order_by('id')
    return render(request, 'draws/list.html', {'last_draws' : last_draws})
    # return HttpResponse("Hello world")

def detail(request,draw_id):
    try:
        a = Draw.objects.get(id = draw_id)
        # a.winner_number = int(a.winner_number)

    except:
        raise Http404('Not found')
    try:
        a.winner_number = int(a.winner_number)
    except:
        pass
    all_bets = DrawBets.objects.filter(draw = draw_id)
    new_bets = []
    pn = 1
    count_win = 0
    with_wallet = 0
    with_wallet_win = 0
    for item in all_bets:
        new_bets.append({'pn': pn, 'btc_address': item.btc_address, 'number': item.number})
        pn += 1
        if item.btc_address:
            with_wallet +=1
        if a.winner_number == item.number:
            count_win +=1
            if item.btc_address:
                with_wallet_win +=1
    stata = {'pn' : pn, 'count_win' : count_win, 'with_wallet' : with_wallet, 'with_wallet_win': with_wallet_win, }
    return render(request, 'draws/detail.html', {'draw': a, 'bets': new_bets, 'stata' : stata})

frontend/frontend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} SITE!{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

frontend/frontend/templates/draws/detail.html
{% extends 'base.html' %}
{% block title %}{{draw.block_number}}{% endblock%}

{% block content %}
<div align="center">
<h2>Draw № {{draw.id}}</h2>
    {% if draw.status == 0  %}
<h3>Next draw is on block № {{draw.block_number}}</h3>
    <p>Всего в игре: {{stata.pn}} <br>
    С кошельками: {{stata.with_wallet}}</p>
    {% else %}
<h3>Wining number is {{draw.winner_number}}</h3>
    <p>Всего в игре: {{stata.pn}} <br>
    С кошельками: {{stata.with_wallet}}</p>

    <p>Всего выиграло: {{stata.count_win}}<br>
    С кошельками: {{stata.with_wallet_win}}</p>
{% endif %}

    {% if bets %}
<table border="1" align="center">
    <tr>
        <td>#</td>
        <td align="center">BTC address</td>
        <td>Selected number</td>
    </tr>
    {% for bet in bets %}
    <tr>
        {% if bet.number == draw.winner_number %}
            <td>{{bet.pn}}</td>
            <td align="center"><strong>{{bet.btc_address}}</strong></td>
            <td align="center" ><strong>{{bet.number}}</strong></td>
        {% else %}
            <td>{{bet.pn}}</td>
            <td align="center">{{bet.btc_address}}</td>
            <td align="center" >{{bet.number}}</td>
        {% endif %}
    </tr>
        {% endfor%}
</table>
    {% else %}
<h3>No bets on this draw registered</h3>
    {% endif%}
</div>
{% endblock %}

frontend/frontend/templates/draws/list.html
{% extends 'base.html' %}
{% block title %}All Draws{% endblock%}

{% block content %}
    {% if last_draws %}
<table border="1" align="center">
    <tr>
        <td>Draw</td>
        <td>Block_id</td>
        <td>Winner number</td>
        <td>Date</td>
        <td>Satus</td>
    </tr>
        {% for a in last_draws %}
    <tr>
        <td align="center">{{a.id}}</td>
        <td><a href="{%url 'draws:detail' a.id%}">{{a.block_number}}</a></td>
        <td align="center">{{a.winner_number}}</td>
        <td>{{a.created_at|date:"d-m-Y"}}</td>
        {% if a.status == 1%}
        <td>Завершен</td>
        {% else %}
        <td>В процессе</td>
        {% endif%}

    </tr>
        {% endfor%}
</table>
    {% else %}
        Not found
    {% endif%}
{% endblock %}